username: admin
password: "123456"
log:
  level: info
  filename: test.log


redis:
  host:
  port: 6379
  db: 0,
  password: ""

host: https://test.wareadmin.biyingniao.com
api_host:  https://test.warehouse.biyingniao.com