LOGIN_ROUTE = "/auth/login"
LOGIN_API_ROUTE = "admin/users/login"
INDEX = "app/hello"
SUPPLIER_LIST = "/app/supplier/list"
SUPPLIER_SAVE = "app/supplier/edit"
BRAND_LIST = "/app/brand/list"
BRAND_SAVE = "/app/brand/edit"